### ISSUE TITLE
Connect TXT Controller to another TXT Controller

### ISSUE THREAD

**Issue by christoschronopoulos** [fischertechnik/FT-TXT#13]
Dear fellow-FT enthusiasts,
I am new to FT and currently trying to understand how to connect the TXT controller of the "TXT Discovery Set" to the one from  "Robotics TXT Automation Robots". What I am trying to achieve is to make those two collaborate so for example the 3-axis Robot starts moving only when the Discovery Robot is at the end point of its trail. Something similar to the way the Learning Factory 4.0 works. Is there any way to do something like this? I searched online but I couldn't find any relevant information. Any help would be extremely appreciated. 
Best, Christos

**Comment by CvanLeeuwenFt** [comment]
See my e-mail.

**Comment by christoschronopoulos** [comment]
Hi Carel, thank you for that! I still have so many questions. If BT communication is not available on TXT-Cs, what about WiFi? Can they communicate over WiFi to do something like the Tango example?

**Comment by CvanLeeuwenFt** [comment]
Hi Christos,
On this question I already gave an answer.

No basic ROBOPro element for messaging implemented, you need to develop some ROBOPro SLI extensions with: ip sockets (fast), web sockets or MQTT (slow).



WIFI, BT and USB are the same because the TXT is using them with IP-addresses. However for BT is the IP address fix as AP, USB it is maybe possible to change the IP-address, for IP-Client it is the DHCP-server that allocate an IP-address. If you want to have communication over IP, all the device need to have different IP-addresses in the LAN.

 

Kind regards,

Carel
